services:
    server:
        command:
        -   /entrypoint.sh
        healthcheck:
            test: curl --fail --insecure https://localhost:9443/
        image: openjdk:8u121-jre
        ports:
        -   '9000'
        -   '9443'
        volumes:
        -   ./entrypoint.sh:/entrypoint.sh:ro
        -   ./svc:/svc:ro
    client:
        command:
        -   /entrypoint.sh
        image: ubuntu:14.04
        volumes:
        -   ./entrypoint.sh:/entrypoint.sh:ro
version: '3'
